
#include "common.hpp"
#include "macro.hpp"

/* Dialogs  */
#include "Dialogs\DIALOG_admin.h"
#include "Dialogs\DIALOG_arrest.hpp"
#include "Dialogs\DIALOG_auctionHouse.hpp"
#include "Dialogs\DIALOG_federalReserve.h"
#include "Dialogs\DIALOG_launder.hpp"
#include "Dialogs\DIALOG_vehSteal.h"
#include "Dialogs\RscDisplayShopClothing.hpp"
#include "Dialogs\RscDisplayShopArma.h"
#include "Dialogs\RscDisplayShopVirtual.hpp"
#include "Dialogs\RscDisplayShopVehicles.h"
#include "Dialogs\RscDisplayShopDynMarkers.hpp"
#include "Dialogs\RscDisplayGarage.hpp"
#include "Dialogs\RscDisplayWelcome.hpp"
#include "Dialogs\RscDisplayTablet.hpp"
#include "Dialogs\RscDisplayVehicle.hpp"
#include "Dialogs\RscDisplayComa.hpp"
#include "Dialogs\RscDisplayInteraction.hpp"
#include "Dialogs\RscDisplaySkull.hpp"
#include "Dialogs\RscDisplayPlayerTrade.hpp"
#include "Dialogs\RscDisplayPlayerSearch.hpp"
#include "Dialogs\RscDisplayPlayerTicket.hpp"
#include "Dialogs\RscDisplayPlayerRevokeLicense.hpp"
#include "Dialogs\RscDisplayAtm.hpp"
#include "Dialogs\RscDisplayHousing.hpp"
class RscTitles // Defines custom UI displays.
{
	#include "Hud\HUD_default.hpp"
	#include "Hud\HUD_progressBar.hpp"
	#include "Hud\HUD_itemVirtual.hpp"
};