
#include "common.hpp"

#include "RscDisplays\RscDisplayDefault.hpp"
#include "RscDisplays\RscDisplayDefaultInteraction.hpp"
#include "RscDisplays\RscDisplayDefaultText.hpp"
#include "RscDisplays\RscDisplayDefaultChoice.hpp"

#include "RscDisplays\RscDisplayAuctionHouse.hpp"
#include "RscDisplays\RscDisplayShopClothing.hpp"
#include "RscDisplays\RscDisplayShopArma.hpp"
#include "RscDisplays\RscDisplayShopVirtual.hpp"
#include "RscDisplays\RscDisplayShopVehicles.hpp"
#include "RscDisplays\RscDisplayShopDynMarkers.hpp"
#include "RscDisplays\RscDisplayGarage.hpp"
#include "RscDisplays\RscDisplayWelcome.hpp"
#include "RscDisplays\RscDisplayTablet.hpp"
#include "RscDisplays\RscDisplayVehicle.hpp"
#include "RscDisplays\RscDisplayComa.hpp"
#include "RscDisplays\RscDisplayInteraction.hpp"
#include "RscDisplays\RscDisplayPlayerTrade.hpp"
#include "RscDisplays\RscDisplayPlayerSearch.hpp"
#include "RscDisplays\RscDisplayPlayerTicket.hpp"
#include "RscDisplays\RscDisplayPlayerRevokeLicense.hpp"
#include "RscDisplays\RscDisplayAtm.hpp"
#include "RscDisplays\RscDisplayHousing.hpp"
#include "RscDisplays\RscDisplayVirtualExhange.hpp"
#include "RscDisplays\RscDisplayFuel.hpp"
#include "RscDisplays\RscDisplayProcess.hpp"
#include "RscDisplays\RscDisplayLaunder.hpp"
#include "RscDisplays\RscDisplayArrest.hpp"
#include "RscDisplays\RscDisplayCompanies.hpp"
#include "RscDisplays\RscDisplayStealVehicle.hpp"
#include "RscDisplays\RscDisplayC4.hpp"

class RscTitles
{
	#include "RscTitles\RscTitlePlayer.hpp"
	#include "RscTitles\RscTitleProgress.hpp"
	#include "RscTitles\RscTitleLoot.hpp"
	#include "RscTitles\RscTitleMessage.hpp"
	#include "RscTitles\RscTitleIdentities.hpp"
};
